version: '3.7'

services:
  node0:
    container_name: node0
    build: ./node
    environment:
      MESSAGE: 'hello from instance 0'

  node1:
    container_name: node1
    build: ./node
    environment:
      MESSAGE: 'hello from instance 1'

  nginx0:
    container_name: nginx0
    build: ./nginx
    env_file: ./.env
    ports:
      - '80:80'
    volumes:
      - ${ROOT}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
